apiVersion: v1
kind: Service
metadata:
  name: d4-echo-api
  namespace: d4-echo
  labels:
    app: d4-echo-api
spec:
  type: ClusterIP
  selector:
    app: d4-echo-api
  ports:
    - name: http
      port: 80
      targetPort: http
